### ISSUE TITLE
Add PostgreSQL support.

### ISSUE THREAD

**Issue by rmnaderdev** [PotatoDotJar/Whitelist-Sync-2-Spigot#4]

**Comment by chenyii1120** [comment]
Hi, I'm wondering will this plugin support postgreSQL?

**Comment by rmnaderdev** [comment]
> Hi, I'm wondering will this plugin support postgreSQL?

The support should be in the lastest development version here on GitHub. I have not had time to work out the bugs that exists yet though.

**Comment by rmnaderdev** [comment]
@chenyii1120 Due to some issues with the postgreSQL implementation. I have decided to remove the support from Whitelist Sync for now. It may come back in the future, but it is not working right now.
